import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ClippedDrawer from "@/components/drawer";
import { Typography } from "@mui/material";
import DynamicForm from "@/components/dynamicform";
import ExportExcel from "@/components/exportexcel";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClippedDrawer>
        <Typography>
          test
        </Typography>
        <DynamicForm />
        <ExportExcel />
      </ClippedDrawer>
    </>
  );
}
